### ISSUE TITLE
Wrong path gets encoded in Makefile: /home/conda/feedstock_root/build_artifacts/ruby_1552262701982/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found

### ISSUE THREAD

**Issue by init-js** [gjtorikian/commonmarker#101]
I'm getting a compilation error during bundle install. commonmarker gets pulled as a dependency, and the resulting Makefile points to a compiler that doesn't exist.

```
current directory: /home/ec2-user/miniconda2/envs/biol525D/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.13/ext/commonmarker
make "DESTDIR="
compiling arena.c
make: /home/conda/feedstock_root/build_artifacts/ruby_1552262701982/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found
Makefile:241: recipe for target 'arena.o' failed
make: *** [arena.o] Error 127
```

The `CC=` line in the Makefiles points to that /home/conda/... path which doesn't exist. The compiler it's looking for, `x86_64-conda_cos6-linux-gnu-cc` is installed elsewhere, and is in my $PATH, but in a different folder.

Is there any quick way around this? Is this a conda bug? Would you know where that CC= line gets pulled from?

**Comment by init-js** [comment]
eh. looks like a conda-forge issue. https://github.com/ContinuumIO/anaconda-issues/issues/10547

**Comment by gjtorikian** [comment]
My anaconda don't want none...of another project's bugs. Sorry!
