### ISSUE TITLE
Rename `render_doc` to `parse_doc`

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/commonmarker#104]

**Comment by ioquatix** [comment]
Why not just `parse`?

**Comment by gjtorikian** [comment]
Irrelevant due to https://github.com/gjtorikian/commonmarker/pull/186 which has removed this feature. Users can use https://github.com/gjtorikian/html-pipeline if they wish to iterate over HTML after the fact.

**Comment by ioquatix** [comment]
Okay, fair enough.

If anyone wants the original behaviour, I forked this gem and it has all the original functionality and more: https://github.com/ioquatix/markly
