### ISSUE TITLE
Bug when parse word with spaces in tags

### ISSUE THREAD

**Issue by dixent** [gjtorikian/commonmarker#106]
Hi, I tryed to parse .md file and parse not correct generate node element. Check screenshots. String '**Tambahkan **' did not parse to strong element because has space at the end of word 'Tambahkan'.  
Content: 
![image](https://user-images.githubusercontent.com/25899828/67208458-40827b00-f41e-11e9-8f41-5a449489b953.png)
Result: 
![image](https://user-images.githubusercontent.com/25899828/67208614-80496280-f41e-11e9-853a-9334b41dc6dc.png)

Result:  should be strong type of element. 
Fix that please. 
Thanks:)

**Comment by kivikakk** [comment]
Hey there; this is expected behaviour in CommonMark — see [the reference CommonMark demo](https://spec.commonmark.org/dingus/?text=**Tambahkan%20**) to verify this.

This won't be changed, as it would mean `commonmarker` is no longer CommonMark-compatible.
