### ISSUE TITLE
Should this move to be Rust-backed?

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/commonmarker#107]
This is primarily intended as a question to @kivikakk though I welcome any questions/concerns from other dependents.

Lately, I've been thinking about moving the backing library of this project from a C implementation to a Rust implementation. I have experience [wrapping Rust crates in Ruby gems already](https://www.gjtorikian.com/posts/2017/08/15/wrapping-rust-in-ruby-to-parse-gql/).

Now, I love C. I cut my teeth on C. I think C has a lot to teach programmers about the fundamentals of software. 

But I am old now, and I don't have the time or inclination to think about segfaults and memory leaks. And I like Rust. I think it's great.

Part of my concern about making the switch is that I don't know what lingering implications this might have. I like that [comrak](https://github.com/kivikakk/comrak)'s [stated goal](https://github.com/kivikakk/comrak#related-projects) is to "model the upstream cmark-gfm as closely as possible in terms of code structure." Are there any other issues I should be thinking about? In my mind, as long as the existing test suite passes, everything should be totally fine....right?

**Comment by kivikakk** [comment]
As long as the test suite passes, it should be fine. (And I'm in favour of such a change, definitely!)

I should say, though, that in part due to that design goal, Comrak isn't as performant as the main other CommonMark renderer, [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark). Comparison using `make bench` from cmark (modified to redirect input instead of giving a filename):

```shell
$ make bench PROG=build/src/cmark-gfm
{ for x in `seq 1 20` ; do \
                /usr/bin/env time -p build/src/cmark-gfm </dev/null >/dev/null ; \
                /usr/bin/env time -p build/src/cmark-gfm < bench/benchinput.md >/dev/null ; \
                done \
        } 2>&1  | grep 'real' | awk '{print $2}' | python3 'bench/stats.py'
mean = 1.0915, median = 1.0850, stdev = 0.0556
$ make bench PROG=(which pulldown-cmark)
{ for x in `seq 1 20` ; do \
                /usr/bin/env time -p /Users/kivikakk/.cargo/bin/pulldown-cmark </dev/null >/dev/null ; \
                /usr/bin/env time -p /Users/kivikakk/.cargo/bin/pulldown-cmark < bench/benchinput.md >/dev/null ; \
                done \
        } 2>&1  | grep 'real' | awk '{print $2}' | python3 'bench/stats.py'
mean = 0.6930, median = 0.6900, stdev = 0.0223
$
```

It appears to pass all but one of the current spec tests; Comrak currently passes all but a different one.

**Comment by kivikakk** [comment]
(I guess the other thing is — extension support may vary from `cmark-gfm`. I try to follow it closely in Comrak.)

**Comment by gjtorikian** [comment]
Addressed by https://github.com/gjtorikian/commonmarker/pull/186
