### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by binford2k** [gjtorikian/commonmarker#109]
As of https://github.com/gjtorikian/commonmarker/commit/1fe234820a77cb3f2b26b47971d229d0da92d652, the default operation is to not render embedded HTML. As such, the render options changed from accepting `:SAFE` to accepting `:UNSAFE`. Unfortunately, the [docs don't reflect that](https://www.gjtorikian.com/commonmarker/#label-Render+options).

**Comment by gjtorikian** [comment]
Thanks for the report. I couldn't figure out just yet why the Markdown table is garbled in rdoc, but I did update the content nonetheless.

PS: if Puppet Labs is relying on Commonmarker, please consider sponsoring. Thanks. ✌️
