### ISSUE TITLE
Numbered checklist

### ISSUE THREAD

**Issue by piranna** [gjtorikian/commonmarker#120]
It's possible to create a checklist using GFM like this

```markdown
- [ ] one
- [x] two
```

but it's done using an unordered list. If using a numbered list like

```markdown
1. [ ] one
2. [x] two
```

the list is created, but it's still unordered, when it should be created as an ordered. Is this the correct place to notify of this bug / lack of feature? Or is there a specific repo for it?

**Comment by gjtorikian** [comment]
Hi there! This sounds like an issue for https://github.com/github/cmark-gfm, which implements the checklist extension. This repo is only a Ruby wrapper around that C code.

Good luck!

**Comment by piranna** [comment]
> Hi there! This sounds like an issue for [github/cmark-gfm](https://github.com/github/cmark-gfm), which implements the checklist extension.

I was looking what was the code used by Github, and it seemed it was this Ruby gem, thank you for pointing me to the other repo :-)
