### ISSUE TITLE
Provide access to `refmap`.

### ISSUE THREAD

**Issue by ioquatix** [gjtorikian/commonmarker#121]
I would like to extract link data from the `refmap` but it doesn't seem possible. Can you let me know if it's possible?

**Comment by kivikakk** [comment]
It's possible to add functions to facilitate iteration of the `refmap`, definitely; the structures are defined in public header files and so should be reasonably stable.

**Comment by ioquatix** [comment]
Do you want me to make a PR?

**Comment by kivikakk** [comment]
Yes, please — as long as new code is added to `commonmarker.c` and `commonmarker.h` only, as everything else in `ext/commonmarker/` is copied in from upstream.

**Comment by ioquatix** [comment]
I ended up forking this repo to https://github.com/ioquatix/markly/ and implementing a `Parser` class which can (potentially) expose this. Back porting it will be almost impossible because the interfaces in this code base don't really expose 'per-document' or 'per-parser' so I'm going to close this issue.
