### ISSUE TITLE
Inlines containing a pipe are not properly parsed within table rows

### ISSUE THREAD

**Issue by MatthewHerbst** [gjtorikian/commonmarker#125]
As seen in [this README file](https://github.com/gregnb/react-to-print/blob/master/README.md), the table extension is not properly parsing inlines that contain a `|` character. Specifically, the following line is parsed incorrectly:

```md
| **`pageStyle?`** | `string|function` |  We set some basic styles to help improve page printing. Use this to override them and provide your own. If given as a function, it must return a `string` |
```

In GitHub, which uses this (commonmarker) parser the line above is incorrectly rendered as:

<img width="382" alt="Screen Shot 2020-07-09 at 1 03 25 PM" src="https://user-images.githubusercontent.com/1287375/87085365-9d100b00-c1e4-11ea-981b-b9076ad5d85b.png">

In VSCode using the [Markdown All In One extension](https://github.com/yzhang-gh/vscode-markdown), which uses the [markdown-it](https://github.com/markdown-it/markdown-it) parser, it is properly rendered as:

<img width="1032" alt="Screen Shot 2020-07-09 at 1 06 33 PM" src="https://user-images.githubusercontent.com/1287375/87085620-0859dd00-c1e5-11ea-8b9b-c116f8ae7c38.png">

Code spans ([spec](https://github.github.com/gfm/#code-spans)) are inlines, and inlines should be parsed properly in tables ([spec](https://github.github.com/gfm/#tables-extension-)):

Code span spec:

> A code span begins with a backtick string and ends with a backtick string of equal length. The contents of the code span are the characters between the two backtick strings

Table spec:

> Each row consists of cells containing arbitrary text, in which inlines are parsed, separated by pipes (`|`).

**Comment by MatthewHerbst** [comment]
npm also properly renders the row: https://www.npmjs.com/package/react-to-print

**Comment by kivikakk** [comment]
Read down a little bit in the spec:

> Include a pipe in a cell’s content by escaping it, including inside other inline spans:

It's a bit regrettable that this is the case, but the behaviour as implemented by cmark-gfm/commonmarker is to spec.

**Comment by kivikakk** [comment]
See https://github.com/github/cmark-gfm/issues/100 for links with history on the issue.

**Comment by MatthewHerbst** [comment]
@kivikakk that was a lot of good reading, thanks for those links. Apologies for not reading farther down into the spec, and thanks for helping to maintain everything. A bit frustrating that it is this way, but from those resources I understand why that decision was made. Hard for me to decide if I want the docs to be "right" on GitHub or on npm, I'll likely just use slightly non-standard typing notation to avoid the issue. Now to get all the other parsers to get on the same page... 😄
