### ISSUE TITLE
Potential to cut a new release?

### ISSUE THREAD

**Issue by itsliamegan** [gjtorikian/commonmarker#129]
Since v0.21 doesn't include #127, using the most recent version from RubyGems still causes the warning described in that issue. Would it be possible to release a new version that includes the fix (and of course the other few fixes since v0.21)?

**Comment by gjtorikian** [comment]
Oh definitely, I hadn't realized that. I'll put out a patch now.

**Comment by gjtorikian** [comment]
Done!
