### ISSUE TITLE
In HtmlRenderer, escape_html() returns a string with encoding #<Encoding:ASCII-8BIT>

### ISSUE THREAD

**Issue by andreas12345** [gjtorikian/commonmarker#130]
Hi,

when trying to override `HtmlRenderer#text`, I noticed that the encoding of the string after escape_html() is #<Encoding:ASCII-8BIT>:

```ruby
  def text(node)
    puts node.string_content.encoding.inspect # prints #<Encoding:UTF-8>
    puts escape_html(node.string_content).encoding.inspect # prints #<Encoding:ASCII-8BIT>
  end
```

A workaround I used was to apply `force_encoding('utf-8')` before continuing processing of the string.

- Andreas

**Comment by kivikakk** [comment]
Thanks for reporting this! That's a good find. We should probably propagate the encoding of `rb_text` here:

https://github.com/gjtorikian/commonmarker/blob/fc1d7c093c4b8c45a665183e5aefa6a497cc15f3/ext/commonmarker/commonmarker.c#L1150-L1154

(and in a few other places around there.)
