### ISSUE TITLE
Open to removing the ruby-enum dependency?

### ISSUE THREAD

**Issue by bryanp** [gjtorikian/commonmarker#135]
I'd like to propose removing the `ruby-enum` dependency as it unnecessarily increases the footprint of this gem. `ruby-enum` includes `i18n` as a dependency, which itself depends on `concurrent-ruby`. We appear to only use `ruby-enum` in the config objects and don't use much of the functionality it offers. I'd even be willing to do the work of replacing.

Is this a contribution you'd be interested in seeing?

**Comment by gjtorikian** [comment]
Yeah, that sounds good. 👍 Thanks!

**Comment by dblock** [comment]
I've opened https://github.com/dblock/ruby-enum/issues/41 to make the i18n dependency optional.
