### ISSUE TITLE
Escape math environments

### ISSUE THREAD

**Issue by tristone13th** [gjtorikian/commonmarker#136]
It will parse the backslash '\\' in $...$ or $$...$$ thus make the math parsing failed, is there any method to escape the parsing actions inside the math environments?

**Comment by gjtorikian** [comment]
What pipeline are you using to convert math environments? What does the text look like? Escaping the backslash with a backslash (eg. `\\text{}`) _should_ work, but I would need more details.

**Comment by tristone13th** [comment]
> What pipeline are you using to convert math environments? What does the text look like? Escaping the backslash with a backslash (eg. `\\text{}`) _should_ work, but I would need more details.

For example, when I write this

```
$$
\left\{
\begin{aligned}
\frac{w^\intercal x+b}{\|w^\intercal\|} & > d^{w,b} &, y=1 \\
\frac{w^\intercal x+b}{\|w^\intercal\|} & < -d^{w,b} &,  y=-1 \\
\end{aligned}
\right .
$$
```

segment inside a markdown file, it will automatically replace the `\{` with '{' and make the math interpretation failed, how to avoid this?

**Comment by gjtorikian** [comment]
Try entering `\\{` and see if that retains the text. I think you'll need to escape the backslash.

**Comment by tristone13th** [comment]
> Try entering `\\{` and see if that retains the text. I think you'll need to escape the backslash.

Thanks, I think it would be ok but will break the math interpretation on other markdown editors, I will try to find another way to avoid this.

**Comment by gjtorikian** [comment]
Sorry I cannot be of more help.
