### ISSUE TITLE
Direct access to sourcepos on the Node

### ISSUE THREAD

**Issue by danielberndt** [gjtorikian/commonmarker#15]
I'm trying to do some advanced commonmark processing of my users' input and would like to have direct access to the sourcepos attribute on the node.

Right now, the only way I could make it work is to convert the node to html and parse the resulting html:
```
m = /<li data-sourcepos="(\d+):(\d+)-(\d+):(\d+)">)/.match node.to_html(:sourcepos)
```

is there a more direct way to do this?

**Comment by gjtorikian** [comment]
Oh my. I'll expose this.

**Comment by danielberndt** [comment]
Lovely! Thanks a lot!

**Comment by danielberndt** [comment]
:+1:
