### ISSUE TITLE
Allow disabling 4-space code blocks

### ISSUE THREAD

**Issue by marcoms** [gjtorikian/commonmarker#167]
In our Middleman site, we use CommonMarker with partials to allow reusing content, however we have to ensure that none of that content contains 4 spaces to avoid it becoming a code block, which is very tedious. It would be a big help to disable this feature, since we exclusively use code fences instead.

**Comment by gjtorikian** [comment]
If it's not in [the official spec](https://spec.commonmark.org/), we won't support it. Sorry. I would suggest that whatever is inserting the content into your layout (I'm assuming ERB or some such) should strip the whitespace; or use a plugin like https://github.com/gjtorikian/html-pipeline to handle these issues.
