### ISSUE TITLE
latex bug with multiple $ in a line

### ISSUE THREAD

**Issue by rain-1** [gjtorikian/commonmarker#183]
I created this bug at the parent repo. But I believe an issue here may be useful too https://github.com/github/markup/issues/1562

**Comment by kivikakk** [comment]
CommonMarker doesn't do any rendering of LaTeX, so I think this one's just for GitHub's own pipeline.

**Comment by kivikakk** [comment]
Indeed! [cmark-gfm](https://github.com/github/cmark-gfm), which we wrap, has $LaTeX$ **output**:

```console
$ printf '# Hello, world!\n\nLaTeX output from [cmark-gfm](https://github.com/github/cmark-gfm).' | cmark-gfm --to latex
\section{Hello, world!}

LaTeX output from \href{https://github.com/github/cmark-gfm}{cmark-gfm}.
$
```

We build all of cmark-gfm inside CommonMarker, so those source files you're seeing are just those. We don't (yet) expose the ability to render to LaTeX from CommonMarker, though it would be trivial to do so.

This is all quite different to GitHub's offering, which is a MathJax-based (client-side) render. See [Writing mathematical expressions](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions) in GitHub's docs for some information.
