### ISSUE TITLE
Code block incorrectly parsed in commonmarker 1.0.0.pre

### ISSUE THREAD

**Issue by andreas12345** [gjtorikian/commonmarker#202]
Hi,

I noticed that code blocks are sometimes not parsed correctly in commonmarker (1.0.0.pre arm64-darwin):
````
irb(main):011:0> s = "\n```\n\nx\n\n```\n"
=> "\n```\n\nx\n\n```\n"
irb(main):012:0> print(s)

```                                                           
                                                              
x                                                             
                                                              
```                                                           
=> nil                                                        
irb(main):013:0> Commonmarker.to_html(s)
=> "<p>x</p>\n<pre><code></code></pre>\n"
````

The "x" is not inside the generated code & pre tags.

Here is what Comrak CLI 0.15.0 returns for the same piece of Markdown code:
```
<pre style="background-color:#2b303b;"><code>
<span style="color:#c0c5ce;">                                                              
</span><span style="color:#c0c5ce;">x                                                             
</span><span style="color:#c0c5ce;">                                                              
</span>
</code></pre>
```

Thanks,
Andreas

**Comment by kivikakk** [comment]
Thanks for the report. It looks like the [default front-matter delimiter](https://github.com/gjtorikian/commonmarker/blob/a718941b6a55b0ed4ecf10f006d48f4f305e72f7/lib/commonmarker/config.rb#L29) is `""`, rather than unspecified, meaning the first line is getting eaten as frontmatter. The `comrak` execution that produces similar output is:

```console
$ printf "\n```\n\nx\n\n```\n" | comrak --front-matter-delimiter ''
<p>x</p>
<pre style="background-color:#2b303b;"><code>

</code></pre>
```

**Comment by gjtorikian** [comment]
Thanks for reporting this! I was able to also tighten up the string parsing in general. `1.0.0.pre.2` will be released soon.
