### ISSUE TITLE
Description lists not working

### ISSUE THREAD

**Issue by DannyBen** [gjtorikian/commonmarker#216]
I am assuming the Description Lists extension actually means [Definition Lists](https://www.markdownguide.org/extended-syntax/#definition-lists) - I am unable to make it work.

On a side note, perhaps the option key should be renamed to `definition_lists` regardless of how comark calls it?

This code does not produce the expected `<dl>` `<dt>` tags

```ruby
require 'bundler/inline'
gemfile { gem 'commonmarker', '1.0.0.pre6' }

markdown = <<~MARKDOWN
  ~strikethrogh disabled to ensure options accepted~

  Commonmark Definition
  : Ruby wrapper for comrak (CommonMark parser)
MARKDOWN

extensions = { strikethrough: false,  description_lists: true }
options = { extension: extensions, render: { hardbreaks: false } }
output = Commonmarker.to_html markdown, options: options
puts output
```

Output:

```
<p>~strikethrogh disabled to ensure options accepted~</p>
<p>Commonmark Definition
: Ruby wrapper for comrak (CommonMark parser)</p>
```

**Comment by gjtorikian** [comment]
Ah, comrak calls it definition lists: https://github.com/kivikakk/comrak#extensions

I just made the typo here:  https://github.com/gjtorikian/commonmarker/blob/46631023e93466af7aa360cf821ac7b120af47fc/ext/commonmarker/src/options.rs#L100-L102

Thanks for the report, will fix it soon.

**Comment by gjtorikian** [comment]
Ah, actually, I believe this is working as expected.

First, MDN calls `dl`s description lists as well: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

Second, your markdown has an error: there needs to be a paragraph between the term and its definition:

```
    markdown = <<~MARKDOWN
      ~strikethrogh disabled to ensure options accepted~

      Commonmark Definition

      : Ruby wrapper for comrak (CommonMark parser)
    MARKDOWN
 ```

I'll keep the option name as `description_lists`.

**Comment by DannyBen** [comment]
Closing the issues prematurely hints that you are not interested in any input. If I am wasting my time trying to improve this gem, let me know please.

> Second, your markdown has an error: there needs to be a paragraph between the term and its definition:

This statement is wrong.

1. All specs show it without a newline.
2. It does not make sense for it to have a new line, since the title and description are the same item.
3. It is intentionally designed like this, so that renderers that do not support it will simply show it as one paragraph having "Title : Definition".

The first 4 references I found:

- https://www.markdownguide.org/extended-syntax/#definition-lists
- https://www.javatpoint.com/definition-lists-in-markdown
- https://python-markdown.github.io/extensions/definition_lists/
- https://spec-md.com/#sec-Definition-List

**Comment by gjtorikian** [comment]
> Closing the issues prematurely hints that you are not interested in any input. If I am wasting my time trying to improve this gem, let me know please.

You are not wasting your time. Keeping issues open indefinitely stagnates the project. As I have no idea when you'll come back and chastize me or comment or whatever. It helps me know the health of the project: open there's work to do, closed there isn't.

> The first 4 references I found:

You can find as many references as you want, it doesn't matter if the underlying project (comrak) doesn't support it. From [their docs](https://docs.rs/comrak/latest/comrak/struct.ComrakExtensionOptions.html#structfield.description_lists): 

> Each term must be defined in one paragraph, followed by a blank line, and then by the details. Details begins with a colon.

> All specs show it without a newline.

Which specs?
