### ISSUE TITLE
Why is the render option called `unsafe_` and not `unsafe`?

### ISSUE THREAD

**Issue by DannyBen** [gjtorikian/commonmarker#219]
Is this designed to warn (or shame) the user for using it?
Can this be renamed to just `unsafe`?

https://github.com/gjtorikian/commonmarker/blob/13c49c22c46db1ca62a88a798dc7a0561009ffd5/test/test_spec.rb#L12-L14

**Comment by gjtorikian** [comment]
Warn is more likely. The option name was taken straight from comrak: https://github.com/kivikakk/comrak#security

**Comment by DannyBen** [comment]
Two wrongs don't make a right. This is not Ruby like, and the word "unsafe" is warning enough.

**Comment by gjtorikian** [comment]
Ok.

**Comment by kivikakk** [comment]
`unsafe` is a keyword in Rust.
