### ISSUE TITLE
Newlines mysteriously inserted if url is sufficiently long?

### ISSUE THREAD

**Issue by duhaime** [gjtorikian/commonmarker#241]
Hello, we're seeing some strange behavior I'm hoping you can help us diagnose. We have markdown strings and want to convert them to plaintext. However, we want to ensure that the url destinations of links are preserved in the rendered plaintext:

```ruby
md_string = "- [a](https://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com)"

doc = CommonMarker.render_doc(md_string, :DEFAULT, [:autolink])

doc.walk do |node|
  if node.type == :link
    text_node = MarkdownRenderer.text_node(node)
    text_node.string_content = "#{text_node.string_content} (#{node.url})"
    node.insert_before(text_node)
    node.delete
  end
end

doc.to_plaintext
```

This returns: 
```
"  - a (https://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com)\n"
```

There's more leading and trailing whitespace than I'd expect here, but that's fine. What's puzzling is if we add just one more "a" to the url, we get:

```
"  - a\n    (https://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com)\n"
```

(NB: the newline between the link text and the link destination). 

Is there a way to prevent this behavior?

**Comment by gjtorikian** [comment]
Closed due to lack of further info. Feel free to reopen.
