### ISSUE TITLE
Mermaid support in commonmarker

### ISSUE THREAD

**Issue by DaveKriewall** [gjtorikian/commonmarker#253]
I'm building a jekyll-powered web site, and my markdown contains mermaid diagrams.  Using the default markdown renderer `kramdown`, these diagrams appear correctly.  When I switch to commonmarker, I'm getting an image stating that there's a "syntax error in text":

![image](https://github.com/gjtorikian/commonmarker/assets/10441715/1ee3e7d3-9bdb-438c-8f98-3537d9317cc1)

I tried very simple Mermaid diagrams and they all fail in the same way.

I'm using commonmarker 0.23.10.  I upgraded Mermaid to 10.4.0 without any improvement.

Am I missing some additional option?

**Comment by gjtorikian** [comment]
The [commonmarker spec](https://spec.commonmark.org) which this project adheres to, does not support Mermaid diagrams. You can see [the list of additions which Kramdown has made](https://kramdown.gettalong.org/parser/kramdown.html). Your best bet to unblock yourself is to use a JavaScript rendering library like [MathJax](https://www.mathjax.org) or [KaTeX](https://katex.org). Alternatively, you can ask the Kramdown folks how their implementation works, and possibly run a postprocessing script after commonmarker runs to convert the diagrams into SVG or whatever kramdown does.
