### ISSUE TITLE
release for 'ruby' platform is missing since 1.0.0.pre9

### ISSUE THREAD

**Issue by sorah** [gjtorikian/commonmarker#259]
https://rubygems.org/gems/commonmarker/versions

![image](https://github.com/gjtorikian/commonmarker/assets/29440/bf5d5015-3fb1-46fc-9c82-b785f019937e)

Installing prereleased gem on platforms with no prebuilt binary, or forcing compling from source with `BUNDLER_FORCE_RUBY_PLATFORM=true bundle install` and `gem i commonmarker --pre --platform ruby` fails.

**Comment by gjtorikian** [comment]
Sorry about that! I went ahead and pushed for the `ruby` platform, and new releases in the future should also be released for this platform.

<img width="470" alt="Screenshot 2023-11-13 at 15 10 34" src="https://github.com/gjtorikian/commonmarker/assets/64050/c42897b3-2151-4538-a011-da20a40ac0eb">
