### ISSUE TITLE
Building native extensions fails (on Ruby 3.3.0)

### ISSUE THREAD

**Issue by mvz** [gjtorikian/commonmarker#268]
I'm getting a failure when trying to install version 1.0.3 on Ruby 3.3.0:

```
  thread 'main' panicked at 'generate bindings: ClangDiagnostic("/home/matijs/.rbenv/versions/3.3.0/include/ruby-3.3.0/ruby/ruby.h:23:10: fatal error: 'stdarg.h' file not found\n")', /home/matijs/.cargo/registry/src/github.com-1ecc6299db9ec823/rb-sys-0.9.85/build/main.rs:55:6
```

I don't know if the Ruby version is relevant, since installing on older Rubies just downloads the native gem from rubygems.

I do not yet know enough about rb_sys to debug this, so any pointers to what I should try or check are appreciated.

**Comment by mvz** [comment]
I figured it out: I needed to install the `libclang-dev` package. I've created a new issue in `rb-sys` asking for better documentation on this: https://github.com/oxidize-rb/rb-sys/issues/300.

**Comment by gjtorikian** [comment]
xref #270
