### ISSUE TITLE
Undocumented change from CommonMarker to Commonmarker breaks github-markup gem

### ISSUE THREAD

**Issue by mvz** [gjtorikian/commonmarker#269]
In https://github.com/gjtorikian/commonmarker/commit/e93c4514898742e370872e7eb945c16a43e6a5c0#diff-e4e067e2ea2edc2e54365f700843f0871b6c3086e5a1cbd6ec9d6acdf509ddf7, the module name `CommonMarker` was changed to `Commonmarker`. This breaks (at least) the github-markup gem, which assumes the name `CommonMarker`.

I'm filing this bug here since it's not clear if this change was intentional.

**Comment by kivikakk** [comment]
It wasn't explicitly called out as such, but that change happens along with many other breaking API changes; note [0.23.10's usage](https://github.com/gjtorikian/commonmarker/tree/v0.23.10#usage) and [1.0.0's](https://github.com/gjtorikian/commonmarker/tree/v1.0.0#usage).

I'm not 100% certain if that was the exact intention (will let Garen confirm), but I'm assuming so anyway; this is a somewhat clearer path, as it shows `github-markup` assumes the 0.x series and wouldn't work on 1.x without other changes.

**Comment by mvz** [comment]
Thanks @kivikakk that makes sense. This tells me that in any case, github-markup needs to be updated. I have filed an issue here: https://github.com/github/markup/issues/1758.

**Comment by kivikakk** [comment]
Yepyep! Good luck!

**Comment by gjtorikian** [comment]
Yeah because of Zeitwerk and naming conventions I opted to include the case change as a breaking 1.0 change.
