### ISSUE TITLE
Require new release for Ruby 3.3 with binaries

### ISSUE THREAD

**Issue by okuramasafumi** [gjtorikian/commonmarker#270]
https://rubygems.org/gems/commonmarker/versions/1.0.3-arm64-darwin
It seems version `1.0.3` doesn't provide binaries for Ruby 3.3 because the build tool doesn't handle Ruby 3.3 properly. (We can still install this version with Ruby 3.3, but it requires Rust toolchain so we cannot install it on Heroku)
https://github.com/yettoapp/actions/pull/12 was merged and fixed the issue of the build tool, so now we can release the new version so that they provide binaries.

**Comment by rykov** [comment]
Required Ruby version constraint for native builds is `>= 3.1, < 3.3.DEV`, which prevents them from being used with Ruby 3.3.

**Comment by gjtorikian** [comment]
Hi, I am currently waiting for https://github.com/oxidize-rb/rb-sys/pull/298 to be released to ensure that every build dependency supports Ruby 3.3. Please be mindful of the holidays + new year's while we follow this. ☮️

**Comment by rykov** [comment]
Big thanks @gjtorikian for taking care of this so quickly.

**Comment by okuramasafumi** [comment]
@gjtorikian Thank you for releasing it!
