### ISSUE TITLE
`node.string_content` is not utf-8

### ISSUE THREAD

**Issue by danielberndt** [gjtorikian/commonmarker#30]
I just got a bit bitten by this one.

I was just wondering whether there's a reason for why the user of the library has to manually call `node.string_content.force_encoding("utf-8")` to ensure the output is actually utf-8 rather than ascii which was rather unexpected (at least to me)

Cheers :)
Daniel

**Comment by gjtorikian** [comment]
The user should not have to! I'll fix this when I've got the time (unless you want to submit a PR 😉 ).

**Comment by gjtorikian** [comment]
Release 0.13.0 fixes this.
