### ISSUE TITLE
Inconsistency with Comrak on inlines followed by html

### ISSUE THREAD

**Issue by GabeIsman** [gjtorikian/commonmarker#306]
Here's the test string: `_test_<br>test`
```
Comrak: <p><em>test</em><!-- raw HTML omitted -->test</p>
cmark: <p><em>test</em><!-- raw HTML omitted -->test</p>
Commonmarker: <p>_test_<!-- raw HTML omitted -->test</p>
```

It also happens for `strong`s that end in a punctuation mark: `**test.**<br>test`. It doesn't seem to matter what the tag is `_test._<div>test`. 
 
I'm not familiar with Rust but if you point me in the right direction I might be able to help out.

**Comment by gjtorikian** [comment]
I can't reproduce this. What version of Commonmarker are you running?

```
irb(main):001> Commonmarker.to_html("_test_<br>test")
=> "<p><em>test</em><!-- raw HTML omitted -->test</p>\n"
irb(main):002> Commonmarker::VERSION
=> "1.1.4"
```

**Comment by GabeIsman** [comment]
Huh I'm on the same:
```
[94] pry(main)> Commonmarker.to_html("_test_<br>hey")
=> "<p>_test_<!-- raw HTML omitted -->hey</p>\n"
[95] pry(main)> Commonmarker::VERSION
=> "1.1.4"
```
Ruby 3.2.2

**Comment by gjtorikian** [comment]
I reached the same conclusion just now! 1.1.5, released via https://github.com/gjtorikian/commonmarker/issues/306, should have the latest and greatest comrak dependencies. I was indeed running my commands in `main`.  

Please reopen if the problem persists!

**Comment by GabeIsman** [comment]
Great, TY!
