### ISSUE TITLE
Anchors are automatically generated for headings

### ISSUE THREAD

**Issue by tysongach** [gjtorikian/commonmarker#318]
Hello,

I’ve just installed the gem into a Rails app and without passing in any options, Commonmarker is generating HTML headings with an anchor link inside of them:

```
% bin/rails c
Loading development environment (Rails 7.2.1.1)
app(dev)> Commonmarker.to_html("# Foo")
=> "<h1><a href=\"#foo\" aria-hidden=\"true\" class=\"anchor\" id=\"foo\"></a>Foo</h1>\n"
```

I was expecting this:

```html
<h1>Foo</h1>
```

The output is surprising to me because there is no mention of these anchors in the [CommonMark spec](https://spec.commonmark.org/0.31.2/) or in the [GitHub Flavored Markdown spec](https://github.github.com/gfm/).

If you put the example above into the [playground/interactive dingus](https://spec.commonmark.org/dingus/?text=%23%20Foo) on the CommonMark website, it outputs what I was expecting:

```html
<h1>Foo</h1>
```

If you disable the `autolink` extension, the anchor is not generated:

```
app(dev)> Commonmarker.to_html("# Foo", options: { extension: { autolink: false } })
=> "<h1>Foo</h1>\n"
```

However, autolinking is something I _do_ want. Is there a way to disable these heading anchor from being generated, while retaining the standard autolink functionality?

Thanks in advance!

**Comment by gjtorikian** [comment]
Could you try `options: { extension: { header_ids: nil } } `?

**Comment by tysongach** [comment]
@gjtorikian Yep, that removed the anchors for me. Thank you! I wonder if that should be the default?

**Comment by gjtorikian** [comment]
Yes, I’m having a big think about defaults at the moment. Actually #315 is a more general bug around the issue you faced with `autolink: false`. Apparently, the defaults aren’t getting merged correctly, and no one has noticed until now!

**Comment by gjtorikian** [comment]
I documented this in 02840a7c994c767b80917fd01adad9ce6e3a0706.
