### ISSUE TITLE
Table extension with HTML Renderer causes segfault

### ISSUE THREAD

**Issue by deep-spaced** [gjtorikian/commonmarker#34]
Greetings again!

@kivikakk I'm back with another table issue 😢 . Under Ruby 2.3.1, using an HTML Renderer with the table extension enabled at all causes a segfault. Here's a sample test that I set up that causes it every time: https://github.com/deep-spaced/commonmarker/commit/2d0e5770182ac1b80a52e7b420c20f2878bea1ef

To be specific, the latter test causes the segfault to occur: `HtmlRenderer.new.render(doc)`

Here's an example stacktrace: https://gist.github.com/deep-spaced/5e5ceebfed14aaae896bc5180ea89e60

Any thoughts on what might be going on here? Thank you for your time looking into this!

**Comment by kivikakk** [comment]
Looking into this now!

**Comment by kivikakk** [comment]
The table extension currently uses the `user_data` section of the node to store table-related information, which CommonMarker also uses in `rb_node_to_value` and related functions. I'll make these play a little nicer with each other!

**Comment by kivikakk** [comment]
The "quickest" fix is to remove all the node caching in userdata, though it probably has some big memory/speed implications for using the node iterators on larger documents. @gjtorikian; do you have any thoughts on this?

Ideally we'd have separate per-node user-data addressable by a constant or something, but that's a big thing to want to add to cmark.

**Comment by kivikakk** [comment]
There's a look at what this would look like at https://github.com/gjtorikian/commonmarker/compare/table_render_crash (based on @deep-spaced's test branch).

**Comment by kivikakk** [comment]
Dropping the cache has the result that GC ends up prematurely cleaning things up, so it's not good enough.

**Comment by kivikakk** [comment]
The separate "extension data" field pretty much already exists, because the `as` union is unused for extension nodes. Easy solution. :)

**Comment by kivikakk** [comment]
:gem: 0.14.3 is pushed, which fixes this issue! Thank you for reporting it, this has helped me clean up our extensions to cmark :)

**Comment by deep-spaced** [comment]
@kivikakk Thank you so much for jumping on this and fixing it!!! :thumbsup: :thumbsup:
