### ISSUE TITLE
option ':default' does not exist for CommonMarker::Config::Render

### ISSUE THREAD

**Issue by raphink** [gjtorikian/commonmarker#37]
Using 0.14.8 according to [doc](https://www.gjtorikian.com/commonmarker/#label-Converting+to+HTML):

```ruby
irb(main):001:0> require 'commonmarker'
=> true
irb(main):002:0> CommonMarker.render_html('Hi *there*', :default)
TypeError: option ':default' does not exist for CommonMarker::Config::Render
	from /var/lib/gems/2.3.0/gems/commonmarker-0.14.8/lib/commonmarker/config.rb:39:in `check_option'
	from /var/lib/gems/2.3.0/gems/commonmarker-0.14.8/lib/commonmarker/config.rb:26:in `process_options'
	from /var/lib/gems/2.3.0/gems/commonmarker-0.14.8/lib/commonmarker.rb:23:in `render_html'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
```

**Comment by raphink** [comment]
Ah, I see https://github.com/gjtorikian/commonmarker/commit/d758e2c32c68ea1844cd4dadcc4101f2cdf87439

It's not in the online doc though...

**Comment by gjtorikian** [comment]
Yes, sorry, the dependency that handled these options broke semantic versioning and made it so that all symbol names must be upper cases.

I made the change [in the README](https://github.com/gjtorikian/commonmarker/blob/master/README.md#parse-options) but I'll regenerate the API docs too. Thanks!

**Comment by raphink** [comment]
@gjtorikian is there a way to make this backward-compatible? Such a change breaks the API completely from one version to the next

**Comment by gjtorikian** [comment]
I'm at the mercy of https://github.com/dblock/ruby-enum on that.
