### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by sethherr** [gjtorikian/commonmarker#39]
I'm getting an encoding error (when using this with `github-markup`):

```
Encoding::UndefinedConversionError:  "\xE2" from ASCII-8BIT to UTF-8
```
stacktrace:

```
commonmarker-0.14.12/lib/commonmarker.rb:24:in `encode'
commonmarker-0.14.12/lib/commonmarker.rb:24:in `render_html'
github-markup-1.4.7/lib/github/markup/markdown.rb:8:in `block in <class:Markdown>'
github-markup-1.4.7/lib/github/markup/markdown.rb:47:in `render'
github-markup-1.4.7/lib/github/markup.rb:51:in `render_s'
```

I fixed it by calling `.force_encoding('utf-8')` on the string:

```
GitHub::Markup.render_s(GitHub::Markups::MARKUP_MARKDOWN, text.force_encoding('utf-8'))
```

 But it seems like that shouldn't be required...

**Comment by kivikakk** [comment]
Can you give an example input that causes this? I'd like to track this down. In general, you should be feeding commonmarker UTF-8 input.

**Comment by sethherr** [comment]
I tried to print it out and couldn't get it (despite replicating this multiple times on two computers).

And now, after removing the `force_encoding`, it just isn't doing it. So I'm closing the issue. Sorry!
