### ISSUE TITLE
Bold link in italics followed by a period

### ISSUE THREAD

**Issue by regseb** [gjtorikian/commonmarker#53]
Hello,

A bold link in italics followed by a period prints a roman regular link wrapped by `***`.

This code :

```ruby
require 'commonmarker'

print(CommonMarker.render_html('***[foo](http://bar.baz/)***.', :DEFAULT))

print(CommonMarker.render_html('***[foo](http://bar.baz/)***', :DEFAULT))
print(CommonMarker.render_html('**[foo](http://bar.baz/)**.', :DEFAULT))
print(CommonMarker.render_html('*[foo](http://bar.baz/)*.', :DEFAULT))
print(CommonMarker.render_html('***foo***.', :DEFAULT))
```

prints :

> <p>***<a href="http://bar.baz/">foo</a>***.</p>
> <p><em><strong><a href="http://bar.baz/">foo</a></strong></em></p>
> <p><strong><a href="http://bar.baz/">foo</a></strong>.</p>
> <p><em><a href="http://bar.baz/">foo</a></em>.</p>
> <p><em><strong>foo</strong></em>.</p>

**Comment by gjtorikian** [comment]
Hello! Good catch. This appears to be a problem upstream with [the C cmark lib](https://github.com/jgm/cmark/). This Ruby gem simply wraps that C library, so I would suggest opening an issue up there. 

I was able to confirm this with these two links generating text which also follow the CommonMark spec:

* `http://spec.commonmark.org/dingus/?text=***%5Bfoo%5D(http%3A%2F%2Fbar.baz%2F)***`
* `http://spec.commonmark.org/dingus/?text=***%5Bfoo%5D(http%3A%2F%2Fbar.baz%2F)***.`

**Comment by regseb** [comment]
I open an issue on _cmark_ : https://github.com/commonmark/cmark/issues/237.
