### ISSUE TITLE
Request: mermaid rendering support within markdown

### ISSUE THREAD

**Issue by themightychris** [gjtorikian/commonmarker#63]
Consider adding mermaid support within GH-rendered markdown as requested here: https://github.com/github/markup/issues/533

It would ideally function just as this VS Code extension: https://github.com/mjbvz/vscode-markdown-mermaid

This would provide a maximally-githuby way to explain how systems and processes work. Currently this can only be done by running a local command to render a PNG inserted in the README after each change, which is very cumbersome, doesn't version well, and is a barrier to contributors

**Comment by kivikakk** [comment]
Per https://github.com/github/markup/issues/533#issuecomment-355477733, the correct destination is [the support team](https://github.com/contact). Rendering the diagram doesn't take place in or relate to the Markdown to HTML transformation, which is what this library does.

**Comment by themightychris** [comment]
@kivikakk Gotcha, thanks, I did submit it there too, was hoping this might be an appropriate public place to track the request.

Is it accurate that this is where the rendering would be invoked from though and that a ruby toolchain would be ideal? Or is there a separate project somewhere for handling rendering code blocks based on indicated language?

**Comment by kivikakk** [comment]
@themightychris excellent to hear!

Rendering would not be invoked from here, no; the code block here would be transformed into `<pre lang="…">…</pre>`, where it's then transformed by code internal to GitHub's user content stack. Among other reasons, it's done this way so our code block transformation (i.e. syntax highlighting currently) is consistent no matter what the source language, as more than just Markdown is supported by this stack. (e.g. you might have a `README.pod` or a wiki page in Asciidoc.)

**Comment by themightychris** [comment]
@kivikakk ah that makes sense, thanks so much for the additional detail!

**Comment by kivikakk** [comment]
It's part of GitHub.com's internal code, so it's not published.

**Comment by piranna** [comment]
Oh, what a shame... :-( What about allowing to set an url as the code block language? This way the code block could do a POST request to that url with the content of the code block, and return an html snippet to be replaced in place of the code block, allowing third party code block processors like this one...

**Comment by gjtorikian** [comment]
FWIW you could also use https://github.com/jch/html-pipeline, whose `MarkdownFilter` uses Commonmarker as well, as an open-source alternate rendering pipeline.

We will likely never allow `POST`ing to third party websites.

**Comment by gjtorikian** [comment]
Well, you could create a GitHub App to do that replacement for you: https://github.com/marketplace

Have the App listen to comments, and it edit any comment with a code block matching whatever you're looking to replace.

**Comment by themightychris** [comment]
@gjtorikian a `POST` to a third party website was only brought up as a potential workaround AFAIK. The mermaid renderer is an MIT nodejs app and could be run anywhere: https://github.com/mermaidjs/mermaid.cli

**Comment by piranna** [comment]
> @gjtorikian a POST to a third party website was only brought up as a potential workaround AFAIK

Yes, I suggested it as a workaround, that could be used not only for this but also for other code blocks replacements.

**Comment by rKinson** [comment]
FWIW while trying to find a solution I stumbled across this pre-alpha project https://github.com/neenjaw/mermaid-markdown-test

**Comment by rxaviers** [comment]
![diagram](https://mermaid-js.github.io/mermaid-live-editor/#/view/Z3JhcGggVEQKQVtJc3N1ZV0gLS0+fHRyaWFnZXwgQihpbnZlc3RpZ2F0ZSkKQiAtLT4gQ3tMZXQgbWUgdGhpbmt9CkMgLS0+fEF8IERbc2V2ZXJpdHkgMV0KQyAtLT58QnwgRVtzZXZlcml0eSAyXQpDIC0tPnxDfCBGW3NldmVyaXR5IDNd)
