### ISSUE TITLE
extension tasklist not found

### ISSUE THREAD

**Issue by chrkau** [gjtorikian/commonmarker#64]
It seems the tasklist extension is broken (or rather not available):

```
require 'commonmarker'

CommonMarker.render_html('foo', :DEFAULT, [:tasklist])
```

results in:
```
Traceback (most recent call last):
	2: from test.rb:3:in `<main>'
	1: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commonmarker-0.17.7.1/lib/commonmarker.rb:25:in `render_html'
/usr/local/Cellar/rbenv/1.1.1/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commonmarker-0.17.7.1/lib/commonmarker.rb:25:in `markdown_to_html': extension tasklist not found (ArgumentError)
```

**Comment by kivikakk** [comment]
Yep, this documentation is mistaken. (Now fixed.) `tasklist` isn't actually an extension rendered by the underlying library. Thanks for the report.

**Comment by oliverguenther** [comment]
Tasklist has been merged to cmark end of 2018 (https://github.com/github/cmark-gfm/pull/94). I gave it a go to try and extend the options to add tasklist, but didn't get too far.

**Comment by gjtorikian** [comment]
Thanks for the bump, @oliverguenther. I opened https://github.com/gjtorikian/commonmarker/pull/94 to start looking into this.
