### ISSUE TITLE
Tag 0.17.10 and 0.17.11

### ISSUE THREAD

**Issue by sj26** [gjtorikian/commonmarker#75]
Please tag the releases so compare links work:

https://github.com/gjtorikian/commonmarker/compare/v0.17.9...v0.17.10

https://github.com/gjtorikian/commonmarker/compare/v0.17.10...v0.17.11

**Comment by gjtorikian** [comment]
Done, sorry about that.

@kivikakk seems like there's a mix of `v` prefixed and non-prefixed tags:

```
> git tag -l      
0.16.1
0.16.2
0.16.3
0.16.4
0.16.5
0.16.6
0.16.7
0.16.8
0.16.9
0.17.0
0.17.1
0.17.10
0.17.2
0.17.3
0.17.4
...
v0.16.0
v0.17.10
v0.17.11
v0.17.5
v0.17.6
v0.17.7
v0.17.7.1
```

I think we should probably stick to the `v` series, I think that's the default from `bundle exec release`.

**Comment by kivikakk** [comment]
What a mess. Yep, all tags should definitely start with `v` — my bad.

**Comment by sj26** [comment]
Thanks folks!
