### ISSUE TITLE
100mb test/benchinput.md file is included in published rubygem

### ISSUE THREAD

**Issue by andrew** [gjtorikian/commonmarker#99]
I was experimenting with vendoring some rubygems into a git repository and ran into a problem when trying to push to GitHub:

```
remote: error: File commonmarker/test/benchinput.md is 105.52 MB; this exceeds GitHub's file size limit of 100.00 MB
```

Turns out that https://github.com/gjtorikian/commonmarker/blob/master/commonmarker.gemspec#L21 includes all files in the test directory when publishing, including ones that are ignored by .gitignore, that also includes `test/progit` which is about 25mb.

So excluding those test from the gemspec should significantly reduce the size of the published gem.

**Comment by kivikakk** [comment]
Hm, is this right? It looks like the current gem version is at 146 KB, and has been around there for a long while, with a jump up to 1mb back in Dec 2017 when we did include some extra bits by mistake. Unless you're pulling 0.13.0 from late 2016? There was a 41mb gem by mistake, for sure.

**Comment by kivikakk** [comment]
(But thanks for pointing this out -- I'll make the adjustment to the gemspec.)

**Comment by andrew** [comment]
Thanks! My experiment was vendoring every version of each gem that Octobox depends on, hence the old versions.
